# Generated by Django 3.0.8 on 2020-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EXTC', 'Electronics and Telecommunication'), ('ETRX', 'Electronics')], default='CS', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='CollegeID',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='CollegeName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Contact',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='FirstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='LastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], default='FE', max_length=10),
        ),
    ]
