# Generated by Django 3.0.8 on 2020-10-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CGPA',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4),
        ),
    ]
