# Generated by Django 3.0.8 on 2020-10-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Skills',
            field=models.CharField(choices=[('PYTHON DEV', 'Python Dev'), ('JAVA DEV', 'Java Dev'), ('FRONTEND DEV', 'Frontend Dev'), ('BACKEND DEV', 'Backend Dev'), ('FULLSTACK DEV', 'Fullstack Dev'), ('DATA SCIENTIST', 'Data Scientist')], default='JAVA DEV', max_length=20),
        ),
    ]
