# Generated by Django 3.0.8 on 2020-10-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TPO', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
