# Generated by Django 3.0.8 on 2020-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
