# Generated by Django 3.0.8 on 2020-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO', '0005_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=10),
        ),
    ]
