# Generated by Django 3.0.8 on 2020-10-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO', '0006_auto_20201015_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
