# Generated by Django 3.0.8 on 2020-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPO', '0009_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Domain',
            field=models.CharField(choices=[('PYTHON DEV', 'Python Dev'), ('JAVA DEV', 'Java Dev'), ('FRONTEND DEV', 'Frontend Dev'), ('BACKEND DEV', 'Backend Dev'), ('FULLSTACK DEV', 'Fullstack Dev'), ('DATA SCIENTIST', 'Data Scientist')], default='JAVA DEV', max_length=50),
        ),
    ]
